-- Migration 013: challenges
-- Module 7 (Extended Submitter Base) + Module 3 (Routing Engine)
-- Distinct from the existing `complaints` table:
--   complaints = citizen civic grievances routed to govt workers
--   challenges = societal innovation challenges routed to universities & industry

CREATE TABLE IF NOT EXISTS challenges (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Submitter (extended: citizen, community_org, pri_ulb_official, admin)
  submitted_by           UUID NOT NULL REFERENCES users_profile(id),
  submitter_type         TEXT NOT NULL
                         CHECK (submitter_type IN (
                           'citizen', 'community_org', 'pri_ulb_official',
                           'govt_department', 'admin'
                         )),
  -- Module 7: optional on-behalf-of for PRI/ULB/community submissions
  submitted_on_behalf_of TEXT,

  -- Challenge content
  title                  TEXT NOT NULL,
  description            TEXT NOT NULL,
  domain                 TEXT NOT NULL,   -- e.g. 'Water', 'Health', 'Education', 'Agriculture'
  tags                   TEXT[] NOT NULL DEFAULT '{}',

  -- Routing embedding (Module 3 — generated by Gemini text-embedding-004)
  challenge_embedding    VECTOR(768),     -- NULL until embedding API call completes

  -- Location (reuse PostGIS from migration 012; used as secondary routing filter)
  location               GEOGRAPHY(POINT, 4326),
  district               TEXT,
  state                  TEXT DEFAULT 'Jharkhand',
  address                TEXT,

  -- Media (reuses same storage bucket as complaints)
  image_url              TEXT,
  voice_url              TEXT,
  document_urls          TEXT[] DEFAULT '{}',

  -- Lifecycle state machine (Module 4)
  -- Valid transitions enforced at API layer (proposals/:id/stage route)
  status                 TEXT NOT NULL DEFAULT 'submitted'
                         CHECK (status IN (
                           'submitted',         -- initial state
                           'routed',            -- routing suggestions generated, awaiting human approval
                           'accepted',          -- university accepted the challenge
                           'team_formed',       -- faculty assigned students
                           'proposal_submitted',-- university submitted a formal proposal
                           'in_progress',       -- govt approved proposal, work started
                           'testing',           -- solution in testing/pilot
                           'deployed',          -- solution deployed to field
                           'closed',            -- successfully closed
                           'rejected',          -- terminal: govt or university rejected
                           'stalled'            -- paused: no activity for 30 days
                         )),
  status_updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- Timestamps
  created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at             TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER update_challenges_updated_at
  BEFORE UPDATE ON challenges
  FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- ── Indexes ───────────────────────────────────────────────────────────────
-- pgvector cosine similarity (Module 3 routing engine)
CREATE INDEX IF NOT EXISTS idx_challenges_embedding
  ON challenges
  USING ivfflat (challenge_embedding vector_cosine_ops)
  WITH (lists = 10);

-- Common query patterns
CREATE INDEX IF NOT EXISTS idx_challenges_submitted_by  ON challenges (submitted_by);
CREATE INDEX IF NOT EXISTS idx_challenges_status        ON challenges (status);
CREATE INDEX IF NOT EXISTS idx_challenges_district      ON challenges (district);
CREATE INDEX IF NOT EXISTS idx_challenges_domain        ON challenges (domain);
CREATE INDEX IF NOT EXISTS idx_challenges_created       ON challenges (created_at DESC);

-- ── Row-Level Security ────────────────────────────────────────────────────
ALTER TABLE challenges ENABLE ROW LEVEL SECURITY;

-- Submitters see their own challenges
CREATE POLICY "challenges_submitter_select"
  ON challenges FOR SELECT
  USING (auth.uid() = submitted_by);

-- Submitters can insert (role check done at API layer)
CREATE POLICY "challenges_submitter_insert"
  ON challenges FOR INSERT
  WITH CHECK (auth.uid() = submitted_by);

-- Govt/admin/supervisors/officers can read all challenges
CREATE POLICY "challenges_reviewer_select"
  ON challenges FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM users_profile
      WHERE id = auth.uid()
        AND role IN ('supervisor', 'officer', 'admin')
    )
  );

-- Govt/admin can update status (stage transitions)
CREATE POLICY "challenges_admin_update"
  ON challenges FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM users_profile
      WHERE id = auth.uid()
        AND role IN ('supervisor', 'officer', 'admin')
    )
  );

-- University roles can read challenges routed to their institution
-- (joined via challenge_routing; full enforcement at API layer)
CREATE POLICY "challenges_university_select"
  ON challenges FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM users_profile
      WHERE id = auth.uid()
        AND role IN ('university_admin', 'faculty_mentor', 'student')
    )
  );
