-- Migration 014: challenge_routing
-- Module 3 (Institution-Based Routing Engine)
-- Stores the pgvector-generated ranked routing suggestions and the human-in-the-loop
-- approval decision made by a govt reviewer before the challenge is formally sent to a university.

CREATE TABLE IF NOT EXISTS challenge_routing (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Core references
  challenge_id     UUID NOT NULL REFERENCES challenges(id) ON DELETE CASCADE,
  university_id    UUID NOT NULL REFERENCES universities(id) ON DELETE CASCADE,

  -- Routing metadata (from pgvector cosine similarity query)
  similarity_score NUMERIC(5, 4) NOT NULL,              -- 0.0000–1.0000 cosine similarity
  distance_km      NUMERIC(8, 3),                       -- PostGIS distance, km; NULL if location missing
  rank             SMALLINT NOT NULL,                   -- 1 = best match; up to 5 per challenge

  -- Human-in-the-loop review
  status           TEXT NOT NULL DEFAULT 'suggested'
                   CHECK (status IN (
                     'suggested',  -- generated by routing engine, awaiting reviewer
                     'approved',   -- govt reviewer confirmed: challenge sent to this university
                     'declined',   -- govt reviewer rejected this suggestion
                     'accepted',   -- university accepted the routed challenge
                     'rejected'    -- university declined the routed challenge
                   )),
  reviewed_by      UUID REFERENCES users_profile(id),  -- NULL until a reviewer acts
  reviewed_at      TIMESTAMPTZ,

  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- Enforce: at most one approved routing per (challenge, university) pair
  CONSTRAINT uq_challenge_university UNIQUE (challenge_id, university_id)
);

CREATE TRIGGER update_challenge_routing_updated_at
  BEFORE UPDATE ON challenge_routing
  FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- ── Indexes ───────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_routing_challenge    ON challenge_routing (challenge_id);
CREATE INDEX IF NOT EXISTS idx_routing_university   ON challenge_routing (university_id);
CREATE INDEX IF NOT EXISTS idx_routing_status       ON challenge_routing (status);
-- Fast lookup: pending suggestions for a reviewer's queue
CREATE INDEX IF NOT EXISTS idx_routing_pending
  ON challenge_routing (status, created_at DESC)
  WHERE status = 'suggested';

-- ── Row-Level Security ────────────────────────────────────────────────────
ALTER TABLE challenge_routing ENABLE ROW LEVEL SECURITY;

-- Govt reviewers (supervisor/officer/admin) see all routing rows
CREATE POLICY "routing_reviewer_select"
  ON challenge_routing FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM users_profile
      WHERE id = auth.uid()
        AND role IN ('supervisor', 'officer', 'admin')
    )
  );

-- Govt reviewers can update (approve/decline)
CREATE POLICY "routing_reviewer_update"
  ON challenge_routing FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM users_profile
      WHERE id = auth.uid()
        AND role IN ('supervisor', 'officer', 'admin')
    )
  );

-- Routing engine (service_role via API route) can insert suggestions
-- NOTE: service_role key bypasses RLS — only used server-side in /api routes (doc5 Rule §2)
-- University admins/faculty can see rows where their university is the target
CREATE POLICY "routing_university_select"
  ON challenge_routing FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM universities u
      JOIN users_profile up ON up.id = auth.uid()
      WHERE u.id = university_id
        AND up.role IN ('university_admin', 'faculty_mentor')
    )
  );

-- University roles can update status to accepted/rejected (accept/decline a challenge)
CREATE POLICY "routing_university_update"
  ON challenge_routing FOR UPDATE
  USING (
    status = 'approved'  -- can only act on already-approved suggestions
    AND EXISTS (
      SELECT 1 FROM universities u
      JOIN users_profile up ON up.id = auth.uid()
      WHERE u.id = university_id
        AND up.role IN ('university_admin', 'faculty_mentor')
    )
  );
